name: LuckyVite CI

on:
  push:
    branches: [master]
  pull_request:
    branches: "*"

jobs:
  specs:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        crystal_version: [latest]
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    steps:
      - uses: actions/checkout@v3
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal_version }}
      - name: Run tests
        run: crystal spec
      - name: Check format
        run: crystal tool format --check
      - name: Lint
        run: ./bin/ameba
